baseURL = "https://gfgchlearn.netlify.app"
languageCode = "en-us"
title = "GFGCH Learn"
theme = "learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[minify]
disableHTML = true
